export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_FAILURE = 'FETCH_SERVICES_FAILURE';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const ADD_SERVICE_REQUEST = 'ADD_SERVICE_REQUEST';
export const ADD_SERVICE_FAILURE = 'ADD_SERVICE_FAILURE';
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS';
export const REMOVE_SERVICE_REQUEST = 'REMOVE_SERVICE_REQUEST';
export const REMOVE_SERVICE_FAILURE = 'REMOVE_SERVICE_FAILURE';
export const REMOVE_SERVICE_SUCCESS = 'REMOVE_SERVICE_SUCCESS';
export const FETCH_EDITABLE_SERVICE_REQUEST = 'FETCH_EDITABLE_SERVICE_REQUEST';
export const FETCH_EDITABLE_SERVICE_FAILURE = 'FETCH_EDITABLE_SERVICE_FAILURE';
export const FETCH_EDITABLE_SERVICE_SUCCESS = 'FETCH_EDITABLE_SERVICE_SUCCESS';
export const ADD_EDITED_SERVICE_REQUEST = 'ADD_EDITED_SERVICE_REQUEST';
export const ADD_EDITED_SERVICE_SUCCESS = 'ADD_EDITED_SERVICE_SUCCESS';
export const ADD_EDITED_SERVICE_FAILURE = 'ADD_EDITED_SERVICE_FAILURE';
//

export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const CHANGE_EDITABLE_SERVICE_FIELD = 'CHANGE_EDITABLE_SERVICE_FIELD';
